name: Intiva Firebase App Distribution
on:
  push:
    branches:
      - 'release/**'
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Firebase service account file
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json

      - name: Set Firebase credentials
        run: |
          export "GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-service-account.json" >> $GITHUB_ENV

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Upload release to Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease
